name: Trigger Scanner Workflow

on:
  workflow_dispatch:
    inputs:
      scan_url:
        description: 'URL to scan with the scanner repository'
        required: true

jobs:
  trigger-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger scanner workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: "TanTrumMaster/ApiScanner"  # Ensure this is the correct repository
          token: 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  # Dummy token used directly
          event-type: trigger-scan
          client-payload: '{"scan_url": "${{ github.event.inputs.scan_url }}"}'
