name: Trigger Scanner Workflow

on:
  workflow_dispatch:
    inputs:
      scan_url:
        description: 'URL to scan with the scanner repository'
        required: true

jobs:
  trigger-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger scanner workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: "TanTrumMaster/ApiScanner"  # Correct format for the repository
          token: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token should be sufficient
          event-type: trigger-scan
          client-payload: '{"scan_url": "${{ github.event.inputs.scan_url }}"}'
